In [1]:
input_02 = [
    "1,8,Berlin,2016-07-10,2016-07-11",
    "7,12,London,2016-07-10,2016-07-11",
    "2,29,Berlin,2016-07-10,2016-07-11",
    "1,9,London,2016-07-10,2016-07-11",
    "8,14,Berlin,2016-07-10,2016-07-11",
    "9,6,London,2016-07-10,2016-07-11",
    "2,5,Paris,2016-07-10,2016-07-11",
    "3,21,Tokyo,2016-07-10,2016-07-11",
    "1,16,Paris,2016-07-10,2016-07-11",
    "4,7,Paris,2016-07-10,2016-07-11",
    "6,14,Paris,2016-07-10,2016-07-11"
]

output_02 = [
    "2016-07-10,Paris:4,Berlin:3",
    "2016-07-11,Paris:4,Berlin:3",
]

input_03 = [
    "1,8,Berlin,2016-07-10,2016-07-11",
    "1,12,London,2016-07-10,2016-07-11",
    "1,8,Berlin,2016-07-10,2016-07-11",
    "1,6,London,2016-07-10,2016-07-11",
    "1,14,Berlin,2016-07-10,2016-07-11",
    "1,6,London,2016-07-10,2016-07-11",
    "1,12,Paris,2016-07-10,2016-07-11",
    "1,21,Tokyo,2016-07-10,2016-07-12",
]

output_03 = [
    "2016-07-10,Berlin:1,London:1,Paris:1",
    "2016-07-11,Berlin:1,London:1,Paris:1",
    "2016-07-12,Tokyo:1"
]

input_04 = [
    "1,8,Berlin,2016-07-29,2016-08-02",
    "1,12,London,2016-07-29,2016-08-02",
    "2,29,London,2016-07-30,2016-08-01"
]

output_04 = [
    "2016-07-29,Berlin:1,London:1",
    "2016-07-30,London:2,Berlin:1",
    "2016-07-31,London:2,Berlin:1",
    "2016-08-01,London:2,Berlin:1",
    "2016-08-02,Berlin:1,London:1",
]


input_05 = [
    "1,8,Berlin,2016-07-24,2016-07-25",
    "7,12,London,2016-08-05,2016-08-06",
    "2,29,London,2016-07-24,2016-07-25",
]

output_05 = [
    "2016-07-24,Berlin:1",
    "2016-07-25,Berlin:1",
    "2016-08-05,London:1",
    "2016-08-06,London:1"
]

input_06 = [
    "1,8,London,2016-07-10,2016-07-11",
    "6,8,London,2016-07-10,2016-07-11",
    "2,8,London,2016-07-10,2016-07-11",
    "14,8,London,2016-07-11,2016-07-12",
    "7,8,London,2016-07-11,2016-07-12",
    "16,8,London,2016-07-11,2016-07-12",
]


output_06 = [
    "2016-07-10,London:3",
    "2016-07-11,London:6",
    "2016-07-12,London:3"
]



input_07 = [
    "1,8,Berlin,2016-12-29,2017-01-02",
    "1,12,London,2016-12-29,2017-01-02",
    "2,29,London,2016-12-30,2017-01-01",
]

output_07 = [
    "2016-12-29,Berlin:1,London:1",
    "2016-12-30,London:2,Berlin:1",
    "2016-12-31,London:2,Berlin:1",
    "2017-01-01,London:2,Berlin:1",
    "2017-01-02,Berlin:1,London:1",
]


input_08 = [
    "1,1,Berlin,2016-07-12,2016-07-15",
    "6,17,Amsterdam,2016-09-24,2016-09-26",
    "6,28,Berlin,2016-07-12,2016-07-15",
    "2,6,London,2016-09-14,2016-09-16",
    "32,15,Paris,2016-08-28,2016-08-30",
    "7,2,London,2016-07-11,2016-07-14",
    "17,24,London,2016-12-06,2016-12-09",
    "1,9,Paris,2016-11-10,2016-11-15",
    "2,19,Amsterdam,2016-12-29,2017-01-02",
    
    "17,29,Amsterdam,2016-07-12,2016-07-15",
    "6,25,Amsterdam,2016-08-28,2016-08-30",
    "4,10,London,2016-12-28,2016-12-29",
    
    "19,21,Amsterdam,2016-12-06,2016-12-09",
    "2,26,London,2016-08-28,2016-08-30",
    "4,35,Prague,2016-09-14,2016-09-16",
    "16,11,Amsterdam,2016-11-12,2016-11-15",
    "17,33,Prague,2016-12-06,2016-12-09",
    
    
    "4,13,Berlin,2016-09-14,2016-09-16",
    "31,22,London,2016-09-24,2016-09-26",
    "3,5,Amsterdam,2016-11-14,2016-11-15",
    "2,3,Amsterdam,2016-07-10,2016-07-15",
    "5,16,Berlin,2016-08-29,2016-08-30",
    "6,30,Paris,2016-07-12,2016-07-15",
    "1,27,Berlin,2016-08-28,2016-08-30",
    
    
    "23,18,London,2016-12-29,2017-01-02",
    "11,23,Amsterdam,2016-11-10,2016-11-15",
    "15,31,Amsterdam,2016-12-06,2016-12-09",
    "21,14,Amsterdam,2016-07-10,2016-07-12",
    "3,8,Berlin,2016-11-11,2016-11-13",
    "5,7,Paris,2016-11-10,2016-11-11",
    "5,32,Tokyo,2016-12-06,2016-12-09",
    "8,12,Paris,2016-12-06,2016-12-09",
    "5,34,Amsterdam,2016-09-14,2016-09-16",
    "1,4,London,2016-09-14,2016-09-15",
    "6,20,Paris,2016-12-29,2017-01-02",
]

output_08 = [
  "2016-07-10,Amsterdam:2",
  "2016-07-11,Amsterdam:2,London:1",
  "2016-07-12,Amsterdam:3,Berlin:2,London:1,Paris:1",
  "2016-07-13,Amsterdam:2,Berlin:2,London:1,Paris:1",
  "2016-07-14,Amsterdam:2,Berlin:2,London:1,Paris:1",
  "2016-07-15,Amsterdam:2,Berlin:2,Paris:1",
  "2016-08-28,Amsterdam:1,Berlin:1,London:1,Paris:1",
  "2016-08-29,Berlin:2,Amsterdam:1,London:1,Paris:1",
  "2016-08-30,Berlin:2,Amsterdam:1,London:1,Paris:1",
  "2016-09-14,London:2,Amsterdam:1,Berlin:1,Prague:1",
  "2016-09-15,London:2,Amsterdam:1,Berlin:1,Prague:1",
  "2016-09-16,Amsterdam:1,Berlin:1,London:1,Prague:1",
  "2016-09-24,Amsterdam:1,London:1",
  "2016-09-25,Amsterdam:1,London:1",
  "2016-09-26,Amsterdam:1,London:1",
  "2016-11-10,Paris:2,Amsterdam:1",
  "2016-11-11,Paris:2,Amsterdam:1,Berlin:1",
  "2016-11-12,Amsterdam:2,Berlin:1,Paris:1",
  "2016-11-13,Amsterdam:2,Berlin:1,Paris:1",
  "2016-11-14,Amsterdam:3,Paris:1",
  "2016-11-15,Amsterdam:3,Paris:1",
  "2016-12-06,Amsterdam:2,London:1,Paris:1,Prague:1",
  "2016-12-07,Amsterdam:2,London:1,Paris:1,Prague:1",
  "2016-12-08,Amsterdam:2,London:1,Paris:1,Prague:1",
  "2016-12-09,Amsterdam:2,London:1,Paris:1,Prague:1",
  "2016-12-28,London:1",
  "2016-12-29,London:2,Amsterdam:1,Paris:1",
  "2016-12-30,Amsterdam:1,London:1,Paris:1",
  "2016-12-31,Amsterdam:1,London:1,Paris:1",
  "2017-01-01,Amsterdam:1,London:1,Paris:1",
  "2017-01-02,Amsterdam:1,London:1,Paris:1",
]

d = {
    "input_02": output_02,
    "input_03": output_03,
    "input_04": output_04,
    "input_05": output_05,
    "input_06": output_06,
    "input_07": output_08,
    "input_07": output_08,
}

In [4]:
from collections import OrderedDict

#goal is to organize first by date, then by number of people who visit each city on a particular day
#key must be date, but key must also be city within that date. store users as a set to prevent duplicates and O(1) time access


def pop(N, arr):
    obj = dict()
    
    for item in arr:
        user_id, listing_id, city, start_date, end_date = item.split(',')
        curr_date = s_to_date(start_date)
        
        #until we reach the end of the date
        while (curr_date <= s_to_date(end_date)):
            curr_date_s = date_to_s(curr_date)
            #add user and city in obj
            if curr_date_s in obj:
                if city in obj[curr_date_s]:
                    obj[curr_date_s][city].add(user_id)
                else:
                    obj[curr_date_s][city] = set()
                    obj[curr_date_s][city].add(user_id)
            else:
                obj[curr_date_s] = dict()
                new_s = set()
                new_s.add(user_id)
                obj[curr_date_s][city] = new_s
            
            curr_date = add_one_day(curr_date)
    
    
    obj = OrderedDict(sorted(obj.items()))
    
    
    res = []

    for date in obj:
        sorted_set = sorted(sorted(obj[date]), key=lambda city: len(obj[date][city]), reverse=True)
        top_n = sorted_set[0:N]
        s = build_string(obj, date, top_n)
        res.append(s)
        
    return res


def add_one_day(date):
    return date + timedelta(days=1)

def date_to_s(parsed_date):
    return datetime.strftime(parsed_date, "%Y-%m-%d")

def s_to_date(date):
    return datetime.strptime(date, "%Y-%m-%d")

def build_string(obj, date, arr):
    s = ""
    s += date
    s += ","
    for i in range(len(arr)):
        city = arr[i]

        s += city
        s += ":"
        s += str(len(obj[date][city]))
        if (i < len(arr) - 1):
            s += ","
    return s

In [5]:
#their sol
from datetime import datetime
from datetime import timedelta

def parseDateString(dateStr):
    return datetime.strptime(dateStr, '%Y-%m-%d')

def dateToString(date):
    return date.strftime('%Y-%m-%d')

def popular(num, requests):
    dateStrToCity = dict()
    
    for request in requests:
        user_id, listing_id, city, start_date, end_date = request.split(',')
        date = parseDateString(start_date)
        
        while date <= parseDateString(end_date):
            dateStr = dateToString(date)
            if dateStr not in dateStrToCity:
                dateStrToCity[dateStr] = dict()
            if city not in dateStrToCity[dateStr]:
                dateStrToCity[dateStr][city] = set()
                
            dateStrToCity[dateStr][city].add(user_id)
            date += timedelta(days=1)
            
    ret = []
    
    
    for date in dateStrToCity:
        def scoreCity(city):
            return len(dateStrToCity[date][city])

        def compareCities(city1, city2):
            s1, s2 = scoreCity(city1), scoreCity(city2)

            if s1 != s2:
                return s2-s1
            if city1 < city2:
                return -1
            return 1
        
        s = date + ','
        
        cities=sorted([city for city in dateStrToCity[date]], cmp=compareCities)
        for i, city in enumerate(cities):
            s += city
            s += ':'
            s += str(scoreCity(city))
            s += ','
            if i + 1 == num:
                break
        s = s[:-1]
        
        ret.append(s)
        
    ret = sorted(ret)
    return ret

In [7]:

print(pop(2, input_02) == output_02)
print(pop(3, input_03) == output_03)
print(pop(2, input_04) == output_04)
print(pop(1, input_05) == output_05)
print(pop(2, input_06) == output_06)
print(pop(2, input_07) == output_07)
print(pop(4, input_08) == output_08)

print(output_02 == popular(2, input_02))
print(output_03 == popular(3, input_03))
print(output_04 == popular(2, input_04) )
print(output_05 == popular(1, input_05))
print(output_06 == popular(2, input_06))
print(output_07 == popular(2, input_07))
print(output_08 == popular(4, input_08))

True
True
True
True
True
True
True
True
True
True
True
True
True
True